version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - falkordb
    environment:
      - REDIS_HOST=falkordb
      - REDIS_PORT=6379
      - REDIS_PASSWORD=simplifier

  falkordb:
    image: falkordb/falkordb:latest
    environment:
      - REDIS_ARGS=--requirepass simplifier
    ports:
      - "6379:6379"